- name: Checkstyle for Java
  # You may pin to the exact commit or the version.
  # uses: dbelyaev/action-checkstyle@5cebbb38d3299106432b5b64969a9a94cd5370e2
  uses: dbelyaev/action-checkstyle@v0.2.1
  with:
    # GITHUB_TOKEN
    github_token: # optional, default is ${{ github.token }}
    # Working directory relative to the root directory.
    workdir: # optional, default is .
    # Report level for reviewdog [info, warning, error]
    level: # optional, default is info
    # Reporter of reviewdog command [github-pr-check, github-pr-review].
    reporter: # optional, default is github-pr-check
    # Filtering mode for the reviewdog command [added, diff_context, file, nofilter].
Default is added.

    filter_mode: # optional, default is added
    # Exit code for reviewdog when errors are found [true, false]
Default is `false`.

    fail_on_error: # optional, default is false
    # Additional reviewdog flags
    reviewdog_flags: # optional, default is 
    # Checkstyle configuration specifies which ruleset to apply during scan.
There are two built-in configurations in checkstyle: [google_checks.xml, sun_checks.xml].
google_checks.xml configures Checkstyle for the Google coding conventions (https://google.github.io/styleguide/javaguide.html)
sun_checks.xml configures Checkstyle for the Sun coding conventions (https://www.oracle.com/java/technologies/javase/codeconventions-contents.html)

    checkstyle_config: # default is google_checks.xml
